blog/urls.py
from django.urls import path

from blog.views import (
    HomeView,
    PostDetailView,
    AddPostView,
    UpdatePostView,
    DeletePostView,
    AddCategoryView,
    AuthorPostListView,
    categories_view,
    ShowProfileDetailPageView,
    like_post,
    dislike_post,
)

app_name = "blog"

urlpatterns = [
    path("", HomeView.as_view(), name="index"),
    path("post/<int:pk>", PostDetailView.as_view(), name="post-detail"),
    path(
        "user/<str:username>",
        AuthorPostListView.as_view(),
        name="user-posts"
    ),
    path(
        "<int:pk>/profile/",
        ShowProfileDetailPageView.as_view(),
        name="detail-profile"
    ),
    path("post/create/", AddPostView.as_view(), name="post-create"),
    path("post/edit/<int:pk>/", UpdatePostView.as_view(), name="post-update"),
    path(
        "post/<int:pk>/remove/", DeletePostView.as_view(), name="post-delete"
    ),
    path(
        "category/create/", AddCategoryView.as_view(), name="category-create"
    ),
    path("category/<str:category>/", categories_view, name="category"),
    path("like/<int:pk>", like_post, name="like-post"),
    path("dislike/<int:pk>", dislike_post, name="dislike-post"),
]

blog_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from user.views import ChangePasswordView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("user/", include("user.urls", namespace="user")),
    path(
        "<int:pk>/password/",
        ChangePasswordView.as_view(),
        name="password-change"
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from user.views import (
    UserRegisterView,
    password_success_view,
    ResetPasswordView,
    ResetPasswordDoneView,
    ResetPasswordConfirmView,
    ResetPasswordCompleteView,
    UserEditView,
    EditProfileView,
    CreateUserProfileView,
)

app_name = "user"

urlpatterns = [
    path(
        "register/",
        UserRegisterView.as_view(),
        name="register"
    ),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="registration/login.html"
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(
            template_name="registration/logout.html"
        ),
        name="logout",
    ),
    path(
        "edit-settings/",
        UserEditView.as_view(),
        name="edit-settings"
    ),
    path(
        "<int:pk>/edit-profile/",
        EditProfileView.as_view(),
        name="edit-profile"
    ),
    path(
        "create-profile/",
        CreateUserProfileView.as_view(),
        name="create-profile"
    ),
    path(
        "password-success/",
        password_success_view,
        name="password-success"
    ),
    path(
        "reset_password/",
        ResetPasswordView.as_view(),
        name="reset_password"
    ),
    path(
        "reset_password_sent/",
        ResetPasswordDoneView.as_view(),
        name="password_reset_done"
    ),
    path(
        "reset/<uidb64>/<token>/",
        ResetPasswordConfirmView.as_view(),
        name="password_reset_confirm"
    ),
    path(
        "reset_password_complete/",
        ResetPasswordCompleteView.as_view(),
        name="password_reset_complete"
    ),
]

templates/includes/navigation.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-blue fixed-top">&#8195;&#8195;
  <a class="navbar-brand mr-5" href="#"><strong>My blog</strong></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:index' %}"><strong>Home</strong> <span class="sr-only">(current)</span></a>
      </li>&#8194;&#8194;

      {% if category_menu %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
            <strong>Categories</strong>
          </a>
          <div class="dropdown-menu">
            {% for category in category_menu %}
              <a class="dropdown-item" href="{% url 'blog:category' category|slugify %}">{{ category }}</a><br>
            {% endfor %}
            {% if user.is_authenticated %}
            <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'blog:category-create' %}"><strong>Add Category</strong></a>
            {% endif %}
          </div>
        </li>
      {% endif %}
      &#8194;
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post-create' %}"><strong>Add Post</strong></a>
        </li>

      {% else %}
        &#8194;
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:register' %}">Sign up</a>
        </li>
        &#8194;&#8194;
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:login' %}">Sign in</a>
        </li>

      {% endif %}

    </ul>

    {% if user.is_authenticated %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          <strong>Hello, <em>{{ user.first_name }} {{ user.last_name }}</em></strong>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
          <a class="dropdown-item" href="{% url 'user:edit-settings' %}">Edit Settings</a>
          {% if user.profile.id %}
            <a class="dropdown-item" href="{% url 'blog:detail-profile' user.profile.id %}">Show Profile</a>
            <a class="dropdown-item" href="{% url 'user:edit-profile' user.profile.id %}">Edit Profile</a>
          {% else %}
            <a class="dropdown-item" href="{% url 'user:create-profile' %}">Create Profile</a>
          {% endif %}
          {% if user.is_staff %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'admin:index' %}">Admin Panel</a>
          {% endif %}
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'user:logout' %}">Sign out</a>
        </div>
      </li>

      <span>
        <img src="{% if user.profile.image %}{{ user.profile.image.url }}
             {% else %}{% static 'images/user.png' %}{% endif %}" alt=""
             width="36" style="border-radius: 50%">
      </span>

    </ul>&#8195;&#8195;
    {% endif %}

  </div>
</nav>
<br>

templates/includes/pagination.html
<div class="container">
  <div class="row">
    <div class="col-md-4"></div>

    <div class="col-md-8">

      <div class="pagination justify-content-center">
        {% if page_obj.has_other_pages %}

          {% if page_obj.has_previous %}

            <a class="btn btn-outline-primary mb-4 mr-1" href="?page=1">&laquo;</a>
            <a class="btn btn-outline-primary mb-4 mr-1" href="?page={{ page_obj.previous_page_number }}">&#8249;</a>
          {% endif %}

          {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
              <a class="btn btn-primary mb-4 mr-1" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
              <a class="btn btn-outline-primary mb-4 mr-1" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
            <a class="btn btn-outline-primary mb-4 mr-1" href="?page={{ page_obj.next_page_number }}">&#8250;</a>
            <a class="btn btn-outline-primary mb-4 mr-1" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
          {% endif %}

        {% endif %}
      </div>

    </div>
  </div>
</div>