blog/urls.py
from django.urls import path

from blog.views import (
    HomeView,
    PostDetailView,
    AddPostView,
    UpdatePostView,
    DeletePostView,
    AddCategoryView,
    AuthorPostListView,
    categories_view,
    ShowProfileDetailPageView,
    like_post,
    dislike_post,
)

app_name = "blog"

urlpatterns = [
    path("", HomeView.as_view(), name="index"),
    path("post/<int:pk>", PostDetailView.as_view(), name="post-detail"),
    path(
        "user/<str:username>",
        AuthorPostListView.as_view(),
        name="user-posts"
    ),
    path(
        "<int:pk>/profile/",
        ShowProfileDetailPageView.as_view(),
        name="detail-profile"
    ),
    path("post/create/", AddPostView.as_view(), name="post-create"),
    path("post/edit/<int:pk>/", UpdatePostView.as_view(), name="post-update"),
    path(
        "post/<int:pk>/remove/", DeletePostView.as_view(), name="post-delete"
    ),
    path(
        "category/create/", AddCategoryView.as_view(), name="category-create"
    ),
    path("category/<str:category>/", categories_view, name="category"),
    path("like/<int:pk>", like_post, name="like-post"),
    path("dislike/<int:pk>", dislike_post, name="dislike-post"),
]

blog_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from user.views import ChangePasswordView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("user/", include("user.urls", namespace="user")),
    path(
        "<int:pk>/password/",
        ChangePasswordView.as_view(),
        name="password-change"
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

blog/models.py
from django.conf import settings
from django.db import models
from ckeditor.fields import RichTextField
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name",)
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    @staticmethod
    def get_absolute_url():
        return reverse("blog:index")


class Post(models.Model):
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="posts"
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="posts"
    )
    title = models.CharField(max_length=255)
    content = RichTextField(blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    snippet = models.CharField(
        max_length=255, default="Click Link Above To Read Blog Post..."
    )
    likes = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="post_likes", blank=True
    )
    dislikes = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="post_dislikes", blank=True
    )

    class Meta:
        ordering = ("-date_created", "author", "title",)

    def __str__(self):
        return self.title

    @staticmethod
    def get_absolute_url():
        return reverse("blog:index")


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments"
    )
    author_name = models.CharField(max_length=255)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("date_added",)

    def __str__(self):
        return f"{self.post.title} - {self.author_name} {self.date_added}"

blog/forms.py
from django import forms
from ckeditor.fields import RichTextField

from blog.models import Post, Comment


class PostForm(forms.ModelForm):
    content = RichTextField()

    class Meta:
        model = Post
        fields = ("title", "category", "content")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control"
        self.fields["content"].widget = forms.Textarea(attrs={"rows": 7})

    def save(self, commit=True):
        comment = super().save(commit=False)
        if self.request and self.request.user.is_authenticated:
            comment.author_name = (
                f"{self.request.user.first_name} {self.request.user.last_name}"
            )
        if commit:
            comment.save()

        return comment


class UpdatePostForm(forms.ModelForm):
    content = RichTextField()

    class Meta:
        model = Post
        fields = ("title", "content")

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.views.generic.edit import FormMixin

from blog.forms import PostForm, UpdatePostForm, CommentForm
from blog.models import Post, Category
from user.models import Author, Profile


class HomeView(ListView):
    model = Post
    template_name = "blog/index.html"
    queryset = Post.objects.select_related("author", "category")
    paginate_by = 5

    def get_context_data(self, *args, **kwargs):
        category_menu = Category.objects.all()
        context = super(HomeView, self).get_context_data(*args, **kwargs)
        context["category_menu"] = category_menu
        return context


def categories_view(request, category):
    category_menu = Category.objects.all()
    queryset = Post.objects.select_related("author", "category")
    category_posts = queryset.filter(
        category__name__icontains=category.replace("-", " "),
    )
    paginator = Paginator(category_posts, 3)
    page = request.GET.get("page")
    category_posts = paginator.get_page(page)
    page_obj = category_posts

    context = {
        "category_menu": category_menu,
        "category": category.replace("-", " "),
        "category_posts": category_posts,
        "page_obj": page_obj
    }

    return render(request, "blog/category.html", context=context)


class AuthorPostListView(ListView):
    model = Post
    template_name = "blog/user_posts.html"
    context_object_name = "posts"
    paginate_by = 2

    def get_queryset(self):
        user = get_object_or_404(Author, username=self.kwargs.get("username"))
        return Post.objects.filter(author=user).order_by("-date_created")

    def get_context_data(self, *args, **kwargs):
        category_menu = Category.objects.all()
        context = (
            super(AuthorPostListView, self)
            .get_context_data(*args, **kwargs)
        )
        context["category_menu"] = category_menu
        return context


class ShowProfileDetailPageView(DetailView):
    model = Profile
    template_name = "blog/user_show_detail_profile.html"

    def get_context_data(self, *args, **kwargs):
        context = (
            super(ShowProfileDetailPageView, self)
            .get_context_data(**kwargs)
        )
        page_user = get_object_or_404(Profile, id=self.kwargs["pk"])
        context["page_user"] = page_user
        return context


class PostDetailView(FormMixin, DetailView):
    model = Post
    form_class = CommentForm
    template_name = "blog/post_detail.html"
    queryset = Post.objects.select_related("author", "category")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    def get_success_url(self, **kwargs):
        return reverse_lazy(
            "blog:post-detail",
            kwargs={"pk": self.get_object().id}
        )

    def get_context_data(self, *args, **kwargs):
        category_menu = Category.objects.all()
        context = super().get_context_data(**kwargs)
        context["category_menu"] = category_menu
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.post = self.get_object()
        self.object.user = (
            self.request.user
            if self.request.user.is_authenticated
            else None
        )
        self.object.save()
        return super().form_valid(form)


class AddPostView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "blog/add_post.html"
    success_url = reverse_lazy("blog:index")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class UpdatePostView(UpdateView):
    model = Post
    form_class = UpdatePostForm
    template_name = "blog/update_post.html"
    success_url = reverse_lazy("blog:index")


class DeletePostView(DeleteView):
    model = Post
    template_name = "blog/delete_post.html"
    success_url = reverse_lazy("blog:index")


class AddCategoryView(CreateView):
    model = Category
    template_name = "blog/add_category.html"
    fields = "__all__"


def like_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user in post.likes.all():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
        if request.user in post.dislikes.all():
            post.dislikes.remove(request.user)

    return redirect("blog:post-detail", pk=post.pk)


def dislike_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user in post.dislikes.all():
        post.dislikes.remove(request.user)
    else:
        post.dislikes.add(request.user)
        if request.user in post.likes.all():
            post.likes.remove(request.user)

    return redirect("blog:post-detail", pk=post.pk)

templates/blog/add_category.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Create A New Category{% endblock %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-md-4"></div>

      <div class="col-md-8">
      {% if user.is_authenticated %}

        <h1>Add Category...</h1>
        <br>

        <form action="" method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <button  class="btn btn-secondary">Add Category</button>
        </form>

      {% else %}

        <h5>You're not allowed here!&#8194;<small><em>(And you know it...)</em></small></h5>


      {% endif %}

      </div>
    </div>
  </div>

{% endblock %}

templates/blog/add_comment.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Add A New Comment{% endblock %}

{% block content %}


  <div class="container">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-8">

        <h1>Add Comment...</h1>
        <br>
        <form action="" method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <button  class="btn btn-secondary">Add Comment</button>
        </form>

      </div>
    </div>
  </div>

{% endblock %}

templates/blog/add_post.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Create A New Post{% endblock %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-md-4"></div>

      <div class="col-md-8">
      {% if user.is_authenticated %}
        {% if user.profile %}
        <h1>Add Post...</h1>
        <br>

        <form action="" method="post">
          {% csrf_token %}
          {{ form.media }}
          {{ form|crispy }}
          <button  class="btn btn-secondary">Add Post</button>
        </form>
        {% else %}
          <h5>You're not allowed here! <small><em>(and you know it...)</em></small></h5>
          <h6 style="color: darkred"><em>...You must create your profile!..</em></h6>

        {% endif %}
      {% endif %}

      </div>
    </div>
  </div>

{% endblock %}

templates/blog/category.html
{% extends "base.html" %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-8">

        {% if category_posts %}
          <h1>Category: <em>{{ category }}</em></h1>
          <br><br>

            {% for post in category_posts %}
              <article class="media content-section">
                {% if post.author.id == post.author_id %}
                  <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}" alt="">
                {% else %}
                  <img class="rounded-circle article-img" src="/media/default.jpg" alt="">
                {% endif %}
                <div class="media-body">
                  <div class="article-metadata">
                    By: <a class="mr-2" href="{% url 'blog:detail-profile' pk=post.author.profile.id %}">{{ post.author.first_name }} {{ post.author.last_name }}</a> -
                    &#8195;<small class="text-muted"><em>{{ post.date_created }}</em></small>
                  </div>
                  <a href="{% url 'blog:post-detail' pk=post.id %}">
                    <h2 class="article-title">{{ post.title }}</h2>
                  </a>
                  <p class="article-content">{{ post.content|safe }}</p>
                </div>
              </article>
            {% endfor %}

        {% else %}
          <h2>Sorry this page does not exist...</h2>
        {% endif %}

      </div>
    </div>
  </div>

{% endblock %}

templates/blog/delete_post.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Delete Post{% endblock %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-md-4"></div>

      <div class="col-md-8">

      {% if user.is_authenticated %}
        {% if user.id == post.author.id %}

          <h1>Delete Post...</h1>
          <br><br>

          <h4>Delete: <em>{{ post.title }}</em></h4>
          <p><strong>Are you sure?</strong></p>

          <form action="" method="post">
            {% csrf_token %}
            <br>
            <button  class="btn btn-danger">Delete Post</button>
            <a href="{% url 'blog:index' %}" class="btn btn-secondary">Cancel</a>
          </form>

        {% else %}
        <h5>You're not allowed here! &#8194;<small><em>(and you know it...)</em></small></h5>
        {% endif %}

      {% else %}
        <h5>You're not allowed here! &#8194;<small><em>(and you know it...)</em></small></h5>
      {% endif %}

      </div>
    </div>
  </div>

{% endblock %}

templates/blog/index.html
{% extends "base.html" %}

{% block content %}

    <div class="container-fluid">
      <div class="row">

        <div class="col-md-5"></div>

        <div class="col-md-7">
          <h1>Post List</h1>
          <br><br>

            {% for post in object_list %}
              <table class="table">
                <tbody>
                  <tr>
                    <td class="table-light">&#8195;<strong>Post title: </strong>&#8194;
                      <a href="{% url 'blog:post-detail' pk=post.id %}">{{ post.title }}</a>
                      <br>
                      &#8195;<strong>Category: <em>&#8194;
                        <a href="{% url 'blog:category' post.category|slugify %}">{{ post.category }}</a>
                      </em></strong>
                    </td>
                  </tr>
                  <tr>
                    <td>&#8195;
                      By: <a href="{% url 'blog:user-posts' post.author.username %}">
                          {{ post.author.first_name }} {{ post.author.last_name }}
                          </a>&#8194;
                        created_at: <em>{{ post.date_created }}</em>
                    </td>
                  </tr>
                  <tr>
                    <td>&#8195;{{ post.snippet }}</td>
                  </tr>
                </tbody>
              </table>
            {% endfor %}

        </div>
      </div>
    </div>

{% endblock %}

templates/blog/post_detail.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-8">

        <article class="media content-section">
          {% if post.author.id == post.author_id %}
            <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}" alt="">
          {% else %}
            <img class="rounded-circle article-img" src="/media/default.jpg" alt="">
          {% endif %}

          <div class="media-body">
            <div class="article-metadata">
              By: <a class="mr-2" href="{% url 'blog:detail-profile' post.author.profile.id %}">{{ post.author.first_name }} {{ post.author.last_name }}</a> -
              &#8195;<small class="text-muted"><em>{{ post.date_created }}</em></small>

              {% if user.is_authenticated %}
                {% if user.id == post.author.id %}
                <div>
                  <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'blog:post-update' pk=post.id %}">Edit</a>
                  <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:post-delete' pk=post.id %}">Delete</a>
                </div>
                {% endif %}
              {% endif %}
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content|safe }}</p>
          </div>
        </article>

        {% if user.is_authenticated %}
          {% if request.user != post.author %}
            <div class="container-fluid">
              <div class="row">

                <div class="col-sm-2">
                  <form method="post" action="{% url 'blog:like-post' post.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn {% if user in post.likes.all %}btn-primary{% else %}btn-outline-primary{% endif %}">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
                        <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"></path>
                      </svg>&nbsp;<em>Like</em>&#8194;{{ post.likes.count }}
                    </button>
                  </form>

                </div>

                <div class="col-sm-3">
                  <form method="post" action="{% url 'blog:dislike-post' post.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn {% if user in post.dislikes.all %}btn-danger{% else %}btn-outline-danger{% endif %}">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-down" viewBox="0 0 16 16">
                        <path d="M8.864 15.674c-.956.24-1.843-.484-1.908-1.42-.072-1.05-.23-2.015-.428-2.59-.125-.36-.479-1.012-1.04-1.638-.557-.624-1.282-1.179-2.131-1.41C2.685 8.432 2 7.85 2 7V3c0-.845.682-1.464 1.448-1.546 1.07-.113 1.564-.415 2.068-.723l.048-.029c.272-.166.578-.349.97-.484C6.931.08 7.395 0 8 0h3.5c.937 0 1.599.478 1.934 1.064.164.287.254.607.254.913 0 .152-.023.312-.077.464.201.262.38.577.488.9.11.33.172.762.004 1.15.069.13.12.268.159.403.077.27.113.567.113.856 0 .289-.036.586-.113.856-.035.12-.08.244-.138.363.394.571.418 1.2.234 1.733-.206.592-.682 1.1-1.2 1.272-.847.283-1.803.276-2.516.211a9.877 9.877 0 0 1-.443-.05 9.364 9.364 0 0 1-.062 4.51c-.138.508-.55.848-1.012.964l-.261.065zM11.5 1H8c-.51 0-.863.068-1.14.163-.281.097-.506.229-.776.393l-.04.025c-.555.338-1.198.73-2.49.868-.333.035-.554.29-.554.55V7c0 .255.226.543.62.65 1.095.3 1.977.997 2.614 1.709.635.71 1.064 1.475 1.238 1.977.243.7.407 1.768.482 2.85.025.362.36.595.667.518l.262-.065c.16-.04.258-.144.288-.255a8.34 8.34 0 0 0-.145-4.726.5.5 0 0 1 .595-.643h.003l.014.004.058.013a8.912 8.912 0 0 0 1.036.157c.663.06 1.457.054 2.11-.163.175-.059.45-.301.57-.651.107-.308.087-.67-.266-1.021L12.793 7l.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315l-.353-.354.353-.354c.047-.047.109-.176.005-.488a2.224 2.224 0 0 0-.505-.804l-.353-.354.353-.354c.006-.005.041-.05.041-.17a.866.866 0 0 0-.121-.415C12.4 1.272 12.063 1 11.5 1z"></path>
                      </svg>&nbsp;<em>Dislike</em>&#8194;{{ post.dislikes.count }}
                    </button>
                  </form>
                </div>

              </div>
            </div>
          {% endif %}
        {% endif %}

        <br><br>
        <a href="{% url 'blog:index' %}" class="btn btn-secondary">Back</a>
        <br><br>
        <hr>

        <h2>Comments...</h2>
          <br><br>
          {% for comment in post.comments.all %}
            <strong>{{ comment.author_name }} - {{ comment.date_added }}</strong><br>
            {{ comment.content }}<br>
            <hr>
          {% empty %}
            No Comments Yet...
            <hr>
          {% endfor %}
          <br><br><br>

      {% if user.is_authenticated %}
        {% if request.user != post.author %}
          <h4><em>Add Comment...</em></h4>
          <br>
          <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button  class="btn btn-secondary">Add Comment</button>
          </form>
        {% endif %}
      {% endif %}

      </div>
    </div>
  </div>

{% endblock %}

templates/blog/update_post.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block title %}Edit Post{% endblock %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-md-4"></div>

      <div class="col-md-8">

      {% if user.is_authenticated %}
        {% if user.id == post.author.id %}

          <h1>Edit Post...</h1>
          <br><br>

          <form action="" method="post">
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <button  class="btn btn-secondary">Edit Post</button>
          </form>

        {% else %}
          <h5>You're not allowed here! &#8194;<small><em>(and you know it...)</em></small></h5>
        {% endif %}

      {% else %}
        <h5>You're not allowed here! &#8194;<small><em>(and you know it...)</em></small></h5>
      {% endif %}

      </div>
    </div>
  </div>

{% endblock %}

templates/blog/user_posts.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-4"></div>

      <div class="col-md-8">

        <h1 class="mb-3">
          User records: <em><u>{{ view.kwargs.username }}</u>
          ({{ page_obj.paginator.count }} post{{ page_obj.paginator.count|pluralize }})</em>
        </h1>
        <br>

        {% for post in posts %}
            <article class="media content-section">
              <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}" alt="">
              <div class="media-body">
                <div class="article-metadata">
                  By: <a class="mr-2" href="{% url 'blog:detail-profile' pk=post.author.profile.id %}">
                    {{ post.author.first_name }} {{ post.author.last_name }}
                  </a>
                  &#8195;<small class="text-muted"><em>{{ post.date_created }}</em></small>
                </div>
                <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content|safe }}</p>
              </div>
            </article>
        {% endfor %}

      </div>
    </div>
  </div>

{% endblock %}

templates/blog/user_show_detail_profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}Show Profile{% endblock %}

{% block content %}

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-5"></div>

      <div class="col-md-7">
        <h1>User Profile...</h1>
        <br><br><br>

        <div class="card mb-3" style="max-width: 900px;">
          <div class="row no-gutters">
            <div class="col-md-4">
              <img src="{{ page_user.image.url }}" alt="...">
            </div>

            <div class="col-md-2"></div>

            <div class="col-md-6">
              <div class="card-body">
                <h5 class="card-title">
                  {{ page_user.user.first_name }} {{ page_user.user.last_name }}
                </h5>
                <p>{{ page_user.user.email }}</p>

                {% if page_user.youtube %}
                    <a href="{{ page_user.youtube }}" target="_blank">
                      <img src="{% static 'images/youtube.png' %}" alt="" style="width: 25px">
                    </a>&#8194;
                {% endif %}

                {% if page_user.facebook %}
                    <a href="{{ page_user.facebook }}" target="_blank">
                      <img src="{% static 'images/facebook.png' %}" alt="" style="width: 25px">
                    </a>&#8194;
                {% endif %}

                {% if page_user.instagram %}
                    <a href="{{ page_user.instagram }}" target="_blank">
                      <img src="{% static 'images/instagram.png' %}" alt="" style="width: 25px">
                    </a>&#8194;
                {% endif %}

                {% if page_user.twitter %}
                    <a href="{{ page_user.twitter }}" target="_blank">
                      <img src="{% static 'images/twitter.png' %}" alt="" style="width: 25px">
                    </a>&#8194;
                {% endif %}

                {% if page_user.telegram %}
                    <a href="{{ page_user.telegram }}" target="_blank">
                      <img src="{% static 'images/telegram.png' %}" alt="" style="width: 25px">
                    </a>
                {% endif %}
                <br><br>

                <h5 class="card-title">About me</h5>
                {{ page_user.bio }}

                <p class="card-text"></p>

                <p class="card-text"><small class="text-muted"></small></p>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

{% endblock %}